from PyQt5 import QtCore, QtGui, QtWidgets


class UiCalculator:
    def ui_setup(self, window):
        window.setObjectName("Calculator")
        window.resize(357, 369)
        window.setMinimumSize(QtCore.QSize(345, 367))
        window.setSizeIncrement(QtCore.QSize(5, 5))
        font = QtGui.QFont()
        font.setFamily("URW Gothic")
        font.setItalic(True)
        window.setFont(font)
        window.setTabletTracking(False)
        window.setFocusPolicy(QtCore.Qt.NoFocus)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("9d5-badly-drawn-thinking-emoji-11562863577r4jcmmnhf9.png"),
                       QtGui.QIcon.Normal, QtGui.QIcon.Off)
        window.setWindowIcon(icon)
        window.setLayoutDirection(QtCore.Qt.LeftToRight)
        window.setAutoFillBackground(False)
        window.setStyleSheet("background-color: rgb(49,49,49);""color: rgb(238, 238, 236);")

        self.centralwidget = QtWidgets.QWidget(window)
        self.centralwidget.setSizeIncrement(QtCore.QSize(0, 0))
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")

        self.button_5 = QtWidgets.QPushButton(self.centralwidget)
        self.button_5.setMinimumSize(QtCore.QSize(52, 35))
        self.button_5.setObjectName("button_5")
        self.gridLayout.addWidget(self.button_5, 3, 1, 1, 1)

        self.button_minus = QtWidgets.QPushButton(self.centralwidget)
        self.button_minus.setMinimumSize(QtCore.QSize(52, 35))
        self.button_minus.setObjectName("button_minus")
        self.gridLayout.addWidget(self.button_minus, 4, 3, 1, 1)

        self.button_close_brackets = QtWidgets.QPushButton(self.centralwidget)
        self.button_close_brackets.setMinimumSize(QtCore.QSize(52, 35))
        self.button_close_brackets.setObjectName("button_close_brackets")
        self.gridLayout.addWidget(self.button_close_brackets, 3, 5, 1, 1)

        self.button_open_brackets = QtWidgets.QPushButton(self.centralwidget)
        self.button_open_brackets.setMinimumSize(QtCore.QSize(52, 35))
        self.button_open_brackets.setObjectName("button_open_brackets")
        self.gridLayout.addWidget(self.button_open_brackets, 3, 4, 1, 1)

        self.button_squareroot = QtWidgets.QPushButton(self.centralwidget)
        self.button_squareroot.setMinimumSize(QtCore.QSize(52, 35))
        font = QtGui.QFont()
        font.setItalic(False)
        self.button_squareroot.setFont(font)
        self.button_squareroot.setObjectName("button_squareroot")
        self.gridLayout.addWidget(self.button_squareroot, 4, 5, 1, 1)

        self.button_div = QtWidgets.QPushButton(self.centralwidget)
        self.button_div.setMinimumSize(QtCore.QSize(52, 35))
        self.button_div.setObjectName("button_div")
        self.gridLayout.addWidget(self.button_div, 2, 3, 1, 1)

        self.button_3 = QtWidgets.QPushButton(self.centralwidget)
        self.button_3.setMinimumSize(QtCore.QSize(52, 35))
        self.button_3.setObjectName("button_3")
        self.gridLayout.addWidget(self.button_3, 4, 2, 1, 1)

        self.button_percent = QtWidgets.QPushButton(self.centralwidget)
        self.button_percent.setMinimumSize(QtCore.QSize(52, 35))
        self.button_percent.setObjectName("button_percent")
        self.gridLayout.addWidget(self.button_percent, 5, 2, 1, 1)

        self.button_8 = QtWidgets.QPushButton(self.centralwidget)
        self.button_8.setMinimumSize(QtCore.QSize(52, 35))
        self.button_8.setObjectName("button_8")
        self.gridLayout.addWidget(self.button_8, 2, 1, 1, 1)

        self.input_screen = QtWidgets.QLabel(self.centralwidget)
        self.input_screen.setEnabled(False)
        self.input_screen.setMinimumSize(QtCore.QSize(330, 60))
        self.input_screen.setMaximumSize(QtCore.QSize(16777215, 60))
        self.input_screen.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.input_screen.setAutoFillBackground(False)
        self.input_screen.setStyleSheet("background-color: rgb(57, 57, 57)")
        self.input_screen.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.input_screen.setFrameShadow(QtWidgets.QFrame.Plain)
        self.input_screen.setLineWidth(1)
        self.input_screen.setMidLineWidth(0)
        self.input_screen.setText("")
        self.input_screen.setScaledContents(False)
        self.input_screen.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.input_screen.setIndent(-1)
        self.input_screen.setObjectName("input_screen")
        self.input_screen.setStyleSheet("QLabel{font-size: 16pt;}")
        self.gridLayout.addWidget(self.input_screen, 1, 0, 1, 6)

        self.button_comma = QtWidgets.QPushButton(self.centralwidget)
        self.button_comma.setMinimumSize(QtCore.QSize(52, 35))
        self.button_comma.setObjectName("button_comma")
        self.gridLayout.addWidget(self.button_comma, 5, 1, 1, 1)

        self.button_mul = QtWidgets.QPushButton(self.centralwidget)
        self.button_mul.setMinimumSize(QtCore.QSize(52, 35))
        self.button_mul.setObjectName("button_mul")
        self.gridLayout.addWidget(self.button_mul, 3, 3, 1, 1)

        self.button_plus = QtWidgets.QPushButton(self.centralwidget)
        self.button_plus.setMinimumSize(QtCore.QSize(52, 35))
        self.button_plus.setObjectName("button_plus")
        self.gridLayout.addWidget(self.button_plus, 5, 3, 1, 1)

        self.button_X2 = QtWidgets.QPushButton(self.centralwidget)
        self.button_X2.setMinimumSize(QtCore.QSize(52, 35))
        font = QtGui.QFont()
        font.setItalic(True)
        self.button_X2.setFont(font)
        self.button_X2.setStyleSheet("")
        self.button_X2.setObjectName("button_X2")
        self.gridLayout.addWidget(self.button_X2, 4, 4, 1, 1)

        self.button_6 = QtWidgets.QPushButton(self.centralwidget)
        self.button_6.setMinimumSize(QtCore.QSize(52, 35))
        self.button_6.setObjectName("button_6")
        self.gridLayout.addWidget(self.button_6, 3, 2, 1, 1)

        self.button_clearall = QtWidgets.QPushButton(self.centralwidget)
        self.button_clearall.setMinimumSize(QtCore.QSize(52, 35))
        self.button_clearall.setObjectName("button_clearall")
        self.gridLayout.addWidget(self.button_clearall, 2, 5, 1, 1)

        self.button_9 = QtWidgets.QPushButton(self.centralwidget)
        self.button_9.setMinimumSize(QtCore.QSize(52, 35))
        self.button_9.setObjectName("button_9")
        self.gridLayout.addWidget(self.button_9, 2, 2, 1, 1)

        self.button_backstep = QtWidgets.QPushButton(self.centralwidget)
        self.button_backstep.setMinimumSize(QtCore.QSize(52, 35))
        font = QtGui.QFont()
        font.setItalic(False)
        self.button_backstep.setFont(font)
        self.button_backstep.setObjectName("button_backstep")
        self.gridLayout.addWidget(self.button_backstep, 2, 4, 1, 1)

        self.button_1 = QtWidgets.QPushButton(self.centralwidget)
        self.button_1.setMinimumSize(QtCore.QSize(52, 35))
        self.button_1.setSizeIncrement(QtCore.QSize(66, 66))
        self.button_1.setObjectName("button_1")
        self.gridLayout.addWidget(self.button_1, 4, 0, 1, 1)

        self.button_0 = QtWidgets.QPushButton(self.centralwidget)
        self.button_0.setMinimumSize(QtCore.QSize(52, 35))
        self.button_0.setObjectName("button_0")
        self.gridLayout.addWidget(self.button_0, 5, 0, 1, 1)

        self.button_equals = QtWidgets.QPushButton(self.centralwidget)
        self.button_equals.setMinimumSize(QtCore.QSize(107, 35))
        self.button_equals.setStyleSheet("background-color: rgb(13,118,29);")
        self.button_equals.setObjectName("button_equals")
        self.gridLayout.addWidget(self.button_equals, 5, 4, 1, 2)

        self.button_4 = QtWidgets.QPushButton(self.centralwidget)
        self.button_4.setMinimumSize(QtCore.QSize(52, 35))
        self.button_4.setObjectName("button_4")
        self.gridLayout.addWidget(self.button_4, 3, 0, 1, 1)

        self.button_2 = QtWidgets.QPushButton(self.centralwidget)
        self.button_2.setMinimumSize(QtCore.QSize(52, 35))
        self.button_2.setObjectName("button_2")
        self.gridLayout.addWidget(self.button_2, 4, 1, 1, 1)

        self.button_7 = QtWidgets.QPushButton(self.centralwidget)
        self.button_7.setMinimumSize(QtCore.QSize(52, 35))
        self.button_7.setObjectName("button_7")
        self.gridLayout.addWidget(self.button_7, 2, 0, 1, 1)

        self.output_screen = QtWidgets.QLabel(self.centralwidget)
        self.output_screen.setMinimumSize(QtCore.QSize(330, 120))
        self.output_screen.setAutoFillBackground(False)
        self.output_screen.setStyleSheet("")
        self.output_screen.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.output_screen.setFrameShadow(QtWidgets.QFrame.Plain)
        self.output_screen.setLineWidth(1)
        self.output_screen.setText("")
        self.output_screen.setScaledContents(True)
        self.output_screen.setStyleSheet("QLabel{font-size: 16pt;}")
        self.output_screen.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.output_screen.setObjectName("output_screen")
        self.gridLayout.addWidget(self.output_screen, 0, 0, 1, 6)

        window.setCentralWidget(self.centralwidget)

        self.retranslateUi(window)
        QtCore.QMetaObject.connectSlotsByName(window)

    def retranslateUi(self, Calculator):
        _translate = QtCore.QCoreApplication.translate
        Calculator.setWindowTitle(_translate("Calculator", "Calculator"))
        self.button_5.setText(_translate("Calculator", "5"))
        self.button_minus.setText(_translate("Calculator", "−"))
        self.button_close_brackets.setText(_translate("Calculator", ")"))
        self.button_open_brackets.setText(_translate("Calculator", "("))
        self.button_squareroot.setText(_translate("Calculator", "√"))
        self.button_div.setText(_translate("Calculator", "÷"))
        self.button_3.setText(_translate("Calculator", "3"))
        self.button_percent.setText(_translate("Calculator", "%"))
        self.button_8.setText(_translate("Calculator", "8"))
        self.button_comma.setText(_translate("Calculator", ","))
        self.button_mul.setText(_translate("Calculator", "×"))
        self.button_plus.setText(_translate("Calculator", "+"))
        self.button_X2.setText(_translate("Calculator", "²"))
        self.button_6.setText(_translate("Calculator", "6"))
        self.button_clearall.setText(_translate("Calculator", "C"))
        self.button_9.setText(_translate("Calculator", "9"))
        self.button_backstep.setText(_translate("Calculator", "↶"))
        self.button_1.setText(_translate("Calculator", "1"))
        self.button_0.setText(_translate("Calculator", "0"))
        self.button_equals.setText(_translate("Calculator", "="))
        self.button_4.setText(_translate("Calculator", "4"))
        self.button_2.setText(_translate("Calculator", "2"))
        self.button_7.setText(_translate("Calculator", "7"))
